# Generated by Django 2.2.4 on 2019-08-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190817_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_comment', to='home.Opinion'),
        ),
    ]
