# Generated by Django 2.2.4 on 2019-08-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190817_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='opinion_id',
        ),
    ]
